### ISSUE TITLE
αστεράκι και επιπλέον στήλη δεν πάνε μαζί

### ISSUE THREAD

**Issue by tmanolat** [pgourdoupi/GrailsMyFirstWebsite#14]
https://github.com/pgourdoupi/GrailsMyFirstWebsite/blob/1a82a701a82d5f534d32f5f1d3e29ebe65d86b8e/grails-app/services/grailsmywebside/EmployeeService.groovy#L15

βάλε ακριβώς τις στήλες που θες - έτσι όπως το έχεις είναι σαν να γυρνά δύο φορές το dob - οπότε παίζει απο σύμπτωση

**Comment by raven99p** [comment]
Μα εφόσον το dob ειναι as dob και δεν αλλαζει το ονομα, δεν ειναι απλα μια "μετονομασία" σε αυτή την περίπτωση?
πχ. Όταν κανω render τα στοιχεία απο αυτη την select μου βγάζει μια στήλη dob απλα με αλλαγμένο format.

**Comment by tmanolat** [comment]
είναι σαν να λες
```
select dob, xxx as dob
from table
```

δεν είναι καλή πρακτική

απο σπόντα η groovy εν προκειμένω καπακώνει σαν τελικο το 2ο (xxx) στο resulted hashmap

και δεν είναι και ευανάγνωστο

οποτε:
- είτε * σκέτο
- είτε named όλες οι στήλες / aliases που θέλουμε
