### ISSUE TITLE
να αφαιρεθεί το background image απο όλες τις σελίδες

### ISSUE THREAD

**Issue by tmanolat** [pgourdoupi/GrailsMyFirstWebsite#16]
και να έχει λευκο / default φοντο

**Comment by raven99p** [comment]
To attribute "for" στο label tag δεν επιλύει το πρόβλημα του focus ακόμα και να υπάρχει background?

**Comment by tmanolat** [comment]
δεν νομίζω να σχετίζεται το background με το for

**Comment by raven99p** [comment]
έχετε γραψει παραπανω, να αφερεθει το background ωστε πατώντας το Label να κανει focus, για αυτό κατάλαβα
 πως σχετίζονται

**Comment by tmanolat** [comment]
ναι - είναι δύο issue σε ένα... εσφαλμένος τίτλος :-)

**Comment by tmanolat** [comment]
το διορθωσα τώρα να είναι ξεκάθαρο - μιας και το είχα βάλει το θέμα του label αλλου...
